# ~/.config/hypr/hyprlock.conf

general {
    # Show a subtle loading bar while auth is happening
    disable_loading_bar = false

    # Seconds you can immediately unlock again without retyping password (0 = none)
    grace = 0

    # Fade-in looks nice; set true to disable
    no_fade_in = false

    # Hide cursor while locked
    hide_cursor = true
}

# No `path` set -> hyprlock uses a live screenshot and blurs it.
background {
    # Increase/decrease blur strength (0 = no blur)
    blur_passes = 5

    # Optional tone tweaks for the blurred screenshot
    contrast = 1.0
    brightness = 0.9
    vibrancy = 0.0
    vibrancy_darkness = 0.0
    monitor = 
    # Uncomment the next line to test with a static image instead of screenshot:
    path = /tmp/hyprlock.png
}

# Central password box
input-field {
    monitor =                # blank = all monitors (hyprlock centers on focused monitor)
    size = 320, 56
    rounding = 12
    outline_thickness = 2

    # Behavior
    fade_on_empty = true
    dots_center = true
    placeholder_text = Password
    font_family = Sans
    font_size = 16

    # Positioning: center of the screen
    valign = center
    halign = center
    position = 0, 0
}

# Date
label {
    monitor = 
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B %Y')" </b>"
    color = $color12
    font_size = 34
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -150
    halign = center
    valign = top
}

# Week
label {
    monitor = 
    text = cmd[update:18000000] echo "<b> "$(date +'Week %U')" </b>"
    color = $color5
    font_size = 24
    font_family = JetBrains Mono Nerd Font 10
    position = 0, -250
    halign = center
    valign = top
}

# Time
label {
    monitor = 
text = cmd[update:1000] echo "<b><big> $(date +"%I:%M:%S %p") </big></b>" # AM/PM
#text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>" # 24H
    color = $color15
    font_size = 94
    font_family = JetBrains Mono Nerd Font 10

    position = 0, 250
    halign = center
    valign = center
}

# User
label {
    monitor = DP-1
    text =    $USER
    color = $color12
    font_size = 18
    font_family = Inter Display Medium

    position = 0, 100
    halign = center
    valign = bottom
}

# uptime
label {
    monitor = DP-1
    text = cmd[update:60000] echo "<b> "$(uptime -p || $Scripts/UptimeNixOS.sh)" </b>"
    color = $color12
    font_size = 24
    font_family = JetBrains Mono Nerd Font 10
    position = 0, 0
    halign = right
    valign = bottom
}

# weather edit specific location. Note, this cause a 2-4 seconds delay in locking
label {
    monitor = DP-1
    text = cmd[update:3600000] [ -f ~/.cache/.weather_cache ] && cat  ~/.cache/.weather_cache
    color = $color12
    font_size = 24
    font_family = JetBrains Mono Nerd Font 10
    position = 50, 0
    halign = left
    valign = bottom
}
