# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAF1EF
background         #19191F
cursor             #B297A3

active_tab_foreground     #19191F
active_tab_background     #FAF1EF
inactive_tab_foreground   #FAF1EF
inactive_tab_background   #19191F

active_border_color   #FAF1EF
inactive_border_color #19191F
bell_border_color     #18152B

color0      #404046
color1		#18152B
color2		#502E41
color3		#874657
color4		#A35262
color5		#1F7490
color6		#B5A29E
color7		#F0E3E0
color8		#A89F9D
color9		#201C39
color10		#6A3D57
color11		#B45E74
color12		#D96E83
color13		#299BC0
color14		#F1D8D2
color15		#F0E3E0
